### PR TITLE
Support laravel 5.2

### PR DESCRIPTION
**Pull request by xian13**
binShared is removed, using singleton instead.
function driver in AuthManager is removed, using auth.driver instead.
Using Guard contract instead of guard implementation.

### CODE REVIEW

**Comment by xian13** [comment]
Hi @jarektkaczyk @L1lle @aedart, because of my fork has some other modifications, I try to create new branch that has commits of laravel 5.2 support.

@jarektkaczyk, I think the error in the CI check is not related to my commit, the error is about Sentinel class not found and my commit is not related to the Sentinel implementation, could you check it?

**Comment by xian13** [comment]
@jarektkaczyk I think this commit explain why the test is fail 4564aae6c851a168072a3484fa7665580713fd3d

**Comment by mvdpoel** [comment]
@jarektkaczyk 
Could this one be fixed please? Would really like to use this package in 5.2 without forking :)

**Comment by jarektkaczyk** [comment]
@mvdpoel I created new branch and tagged version 5.2 - please pull and let me know if all is good.

**Pull request closed without merging**
