### PR TITLE
Store the old value with 'onDelete' listener

### PR DESCRIPTION
**Pull request by carlosviol**
Store the old value with 'onDelete' listener

### CODE REVIEW

**Comment by jarektkaczyk** [comment]
Why? Nothing changes during `onDelete` and `onRestore`?

**Comment by carlosviol** [comment]
Not exactly, It stores an empty array in revisions table. Maybe it needs to
be stored with the right old value and the new value empty, I think. How
about?

Em seg, 25 de mai de 2015 às 14:13, Jarek Tkaczyk notifications@github.com
escreveu:

**Comment by luizpedone** [comment]
@jarektkaczyk I think the issue happens when the application is not using soft delete. When the app really delete the row, it makes sense to store on revisionable log the old values related to that row.

**Comment by carlosviol** [comment]
Exactly, @luizpedone. @jarektkaczyk, it's a situation with normal delete, without soft delete, where is not stored any value at old and new columns. So, I think we need to store the model data in old value. What do you think about?

**Comment by jarektkaczyk** [comment]
@carlosviol @luizpedone Well, the way I see it is, that you don't need it at all when deleting, because you have previous version. Doesn't matter whether it is soft or hard delete.

However, thinking about it now, I can see an edge case, when in fact you don't. That is, when you have such steps:

```
record created
record deleted
```

So, think about it and consider all the options, including edge cases like above, and let me know what you would like it to be. Because if we add `old` to the deleted event, then we should also add `new` for the `created` event for consistency. And so on

**Comment by luizpedone** [comment]
@jarektkaczyk I think we have another edge case you didn't thought. I didn't use Revisionable since the beginning of the project, so I don't have the created type on every item on revision. So if one register is deleted and I don't store the old value, its entirely lost.

The created event already store the new value. At least in my application it's working that way. For example, when I create a new register, it saves something like this:

``` json
{
    "type": "create",
    "old": [],
    "new": {"id": 14, "name": "Luiz Felipe"},
    "table_name": "user"
}
```

Since created event stores the revision data this way, I think storing the deleted event the same way. So, if the register above is deleted, its revision should be something like this:

``` json
{
    "type": "delete",
    "old": {"id": 14, "name": "Luiz Felipe"},
    "new": [],
    "table_name": "user"
}
```

This way, I have two good points to have it this way: (1) keep a more consistent version control of the register since we keep all actions and its changes explicitly and separately, (2) it solves the issue on registers which doesn't contain created event.

By the way, I'm using the version 0.2.5 of the package so it might not be an issue on the Laravel 5 version.

**Comment by dominiquedutra** [comment]
+1 for that.

At this stage I am implementing revisionable in a new project.

Later on I could want to plug it in into existing projects.

**Comment by jarektkaczyk** [comment]
OK, it's done on L5. 

@carlosviol I couldn't merge this one, b/c the event is misspelled (should be `deleted` not `delete`). Pls fix and will be merged

**Comment by luizpedone** [comment]
@jarektkaczyk Thanks! =)

**Comment by carlosviol** [comment]
@jarektkaczyk I didn't understand it. I's sent to "log" with "delete" value, because it's the type of the event, same as create and update, nops?

**Comment by carlosviol** [comment]
Please tell me where you want to change, I will do that ;)

**Comment by jarektkaczyk** [comment]
@carlosviol Nevermind, it's OK. In branch 1.0 the events are fixed to `deleted`, `created` and so on, while  here `create`, `delete` - didn't notice.

**Comment by carlosviol** [comment]
@jarektkaczyk Thanks!

**Comment by carlosviol** [comment]
@jarektkaczyk Can you generate the packagist of this version, please? Thanks!

**Comment by jarektkaczyk** [comment]
@carlosviol Sure, it's done already

**Comment by carlosviol** [comment]
@jarektkaczyk Thanks man!

**Pull request merged**
